
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppInformes
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data/uploads:/data/uploads
    depends_on:
      - mysql

volumes:
  mysql_data:
